services:
  db2:
    image: postgres:latest
    container_name: my_db_prisma
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
